### ISSUE TITLE
Crashing on Pressing "Play" on Windows 10

### ISSUE THREAD

**Issue by 1321302** [rumangerst/SilVerPLuM#11]
Heya =)

Encountered a Crash on windows 10 upon pressing play. Error is that the Cache couldnt be created in the User Folder.
Tried to run SilverPlum as Admin, but that didnt help.

**Comment by rumangerst** [comment]
Does this happen always or only sometimes?

**Comment by 1321302** [comment]
tried it about 6 times now, with compatibility and such.
I guess its some kind of access problem with my Windows, so I could be on my end.

**Comment by rumangerst** [comment]
Are you using mods? Which Windows version? Which Silverplum version? Do you have some sort of log available?

**Comment by 1321302** [comment]
Profile Log from Silverplum:
`[INFO]	program	program	arguments	"E:\\Games\\Steam\\SteamApps\\common\\Stardew Valley\\SilVerPLuM 1-3-2-0\\SilVerPLuM.exe"
[INFO]	profiles	profile	init	Initializing profile default in C:/Users/fl1nt/AppData/Roaming/SilVerPLuM/profiles/default
[INFO]	profiles	profile	init	Initializing profile default in C:/Users/fl1nt/AppData/Roaming/SilVerPLuM/profiles/default
[INFO]	profile	fix-crazyness	inconsistent-executables	Why is the executable on Windows called 'Stardew Valley.exe' and on other platforms 'StardewValley.exe'? I'll copy it.
[INFO]	profile	fix-crazyness	inconsistent-executables	Why is the executable on Windows called 'Stardew Valley.exe' and on other platforms 'StardewValley.exe'? I'll copy it.
[INFO]	modification	repositorylist	load-pipeline	Loaded pipeline repository
[INFO]	modmanager	modmanager	load-mod	Mod repositorylist loaded in profile default
[INFO]	modification	repositorylist	load-pipeline	Loaded pipeline repository
[INFO]	modmanager	modmanager	load-mod	Trying to load mod in C:/Users/fl1nt/AppData/Roaming/SilVerPLuM/profiles/default/mods/repositorylist
[INFO]	modmanager	modmanager	load-mod	Trying to load mod in C:/Users/fl1nt/AppData/Roaming/SilVerPLuM/profiles/default/mods/repositorylist
[INFO]	modmanager	modmanager	load-mod	Mod repositorylist loaded in profile default
[INFO]	savegame	load	load	Loading savegame info in C:/Users/fl1nt/AppData/Roaming/SilVerPLuM/profiles/default/savegames/Nith_116719534
[INFO]	backup-savegame	init	load	Begin to load savegame with id Nith_116719534
[INFO]	savegame	load	load	Loading savegame info in C:/Users/fl1nt/AppData/Roaming/SilVerPLuM/profiles/default/savegames/Nith_116719534
[INFO]	backup-savegame	init	load	Begin to load savegame with id Nith_116719534
[INFO]	savegame	load	load	UID is in C:/Users/fl1nt/AppData/Roaming/SilVerPLuM/profiles/default/savegames/Nith_116719534/Nith_116719534
[INFO]	savegame	load	load	Loading UID
[INFO]	savegame	load	load	UID is in C:/Users/fl1nt/AppData/Roaming/SilVerPLuM/profiles/default/savegames/Nith_116719534/Nith_116719534
[INFO]	savegame	load	load	Loading UID
[INFO]	savegame	load	load	UID is 116719534
[INFO]	savegame	load	load	UID is 116719534
[INFO]	savegame	load	load	Loading savegame info in C:/Users/fl1nt/AppData/Roaming/SilVerPLuM/profiles/default/savegame-backups/Nith_116719534/05-11-2016-15-37-16
[INFO]	savegame	load	load	Loading savegame info in C:/Users/fl1nt/AppData/Roaming/SilVerPLuM/profiles/default/savegame-backups/Nith_116719534/05-11-2016-15-37-16
[INFO]	savegame	load	load	Loading UID
[INFO]	savegame	load	load	UID is in C:/Users/fl1nt/AppData/Roaming/SilVerPLuM/profiles/default/savegame-backups/Nith_116719534/05-11-2016-15-37-16/Nith_116719534
[INFO]	savegame	load	load	Loading UID
[INFO]	savegame	load	load	UID is in C:/Users/fl1nt/AppData/Roaming/SilVerPLuM/profiles/default/savegame-backups/Nith_116719534/05-11-2016-15-37-16/Nith_116719534
[INFO]	savegame	load	load	UID is 116719534
[INFO]	savegame	load	load	UID is 116719534
[INFO]	savegame	load	load	Loading savegame info in C:/Users/fl1nt/AppData/Roaming/SilVerPLuM/profiles/default/savegame-backups/Nith_116719534/05-11-2016-16-12-46
[INFO]	savegame	load	load	Loading savegame info in C:/Users/fl1nt/AppData/Roaming/SilVerPLuM/profiles/default/savegame-backups/Nith_116719534/05-11-2016-16-12-46
[INFO]	savegame	load	load	UID is in C:/Users/fl1nt/AppData/Roaming/SilVerPLuM/profiles/default/savegame-backups/Nith_116719534/05-11-2016-16-12-46/Nith_116719534
[INFO]	savegame	load	load	Loading UID
[INFO]	savegame	load	load	UID is in C:/Users/fl1nt/AppData/Roaming/SilVerPLuM/profiles/default/savegame-backups/Nith_116719534/05-11-2016-16-12-46/Nith_116719534
[INFO]	savegame	load	load	Loading UID
[INFO]	savegame	load	load	UID is 116719534
[INFO]	savegame	load	load	UID is 116719534
[INFO]	savegame	load	load	Loading savegame info in C:/Users/fl1nt/AppData/Roaming/SilVerPLuM/profiles/default/savegame-backups/Nith_116719534/05-11-2016-16-13-00
[INFO]	savegame	load	load	Loading savegame info in C:/Users/fl1nt/AppData/Roaming/SilVerPLuM/profiles/default/savegame-backups/Nith_116719534/05-11-2016-16-13-00
[INFO]	savegame	load	load	Loading UID
[INFO]	savegame	load	load	UID is in C:/Users/fl1nt/AppData/Roaming/SilVerPLuM/profiles/default/savegame-backups/Nith_116719534/05-11-2016-16-13-00/Nith_116719534
[INFO]	savegame	load	load	Loading UID
[INFO]	savegame	load	load	UID is in C:/Users/fl1nt/AppData/Roaming/SilVerPLuM/profiles/default/savegame-backups/Nith_116719534/05-11-2016-16-13-00/Nith_116719534
[INFO]	savegame	load	load	UID is 116719534
[INFO]	savegame	load	load	UID is 116719534
[INFO]	savegame	load	load	Loading savegame info in C:/Users/fl1nt/AppData/Roaming/SilVerPLuM/profiles/default/savegame-backups/Nith_116719534/05-11-2016-16-22-18
[INFO]	savegame	load	load	Loading savegame info in C:/Users/fl1nt/AppData/Roaming/SilVerPLuM/profiles/default/savegame-backups/Nith_116719534/05-11-2016-16-22-18
[INFO]	savegame	load	load	Loading UID
[INFO]	savegame	load	load	UID is in C:/Users/fl1nt/AppData/Roaming/SilVerPLuM/profiles/default/savegame-backups/Nith_116719534/05-11-2016-16-22-18/Nith_116719534
[INFO]	savegame	load	load	UID is in C:/Users/fl1nt/AppData/Roaming/SilVerPLuM/profiles/default/savegame-backups/Nith_116719534/05-11-2016-16-22-18/Nith_116719534
[INFO]	savegame	load	load	Loading UID
[INFO]	savegame	load	load	UID is 116719534
[INFO]	savegame	load	load	UID is 116719534
[INFO]	savegame	load	load	Loading savegame info in C:/Users/fl1nt/AppData/Roaming/SilVerPLuM/profiles/default/savegame-backups/Nith_116719534/05-11-2016-16-22-29
[INFO]	savegame	load	load	Loading savegame info in C:/Users/fl1nt/AppData/Roaming/SilVerPLuM/profiles/default/savegame-backups/Nith_116719534/05-11-2016-16-22-29
[INFO]	savegame	load	load	UID is in C:/Users/fl1nt/AppData/Roaming/SilVerPLuM/profiles/default/savegame-backups/Nith_116719534/05-11-2016-16-22-29/Nith_116719534
[INFO]	savegame	load	load	Loading UID
[INFO]	savegame	load	load	UID is in C:/Users/fl1nt/AppData/Roaming/SilVerPLuM/profiles/default/savegame-backups/Nith_116719534/05-11-2016-16-22-29/Nith_116719534
[INFO]	savegame	load	load	Loading UID
[INFO]	savegame	load	load	UID is 116719534
[INFO]	savegame	load	load	UID is 116719534
[INFO]	savegame	load	load	Loading savegame info in C:/Users/fl1nt/AppData/Roaming/SilVerPLuM/profiles/default/savegame-backups/Nith_116719534/05-11-2016-16-25-33
[INFO]	savegame	load	load	Loading savegame info in C:/Users/fl1nt/AppData/Roaming/SilVerPLuM/profiles/default/savegame-backups/Nith_116719534/05-11-2016-16-25-33
[INFO]	savegame	load	load	Loading UID
[INFO]	savegame	load	load	Loading UID
[INFO]	savegame	load	load	UID is in C:/Users/fl1nt/AppData/Roaming/SilVerPLuM/profiles/default/savegame-backups/Nith_116719534/05-11-2016-16-25-33/Nith_116719534
[INFO]	savegame	load	load	UID is in C:/Users/fl1nt/AppData/Roaming/SilVerPLuM/profiles/default/savegame-backups/Nith_116719534/05-11-2016-16-25-33/Nith_116719534
[INFO]	savegame	load	load	UID is 116719534
[INFO]	savegame	load	load	UID is 116719534
[INFO]	savegame	load	load	Loading savegame info in C:/Users/fl1nt/AppData/Roaming/SilVerPLuM/profiles/default/savegame-backups/Nith_116719534/05-11-2016-16-36-11
[INFO]	savegame	load	load	Loading savegame info in C:/Users/fl1nt/AppData/Roaming/SilVerPLuM/profiles/default/savegame-backups/Nith_116719534/05-11-2016-16-36-11
[INFO]	savegame	load	load	Loading UID
[INFO]	savegame	load	load	Loading UID
[INFO]	savegame	load	load	UID is in C:/Users/fl1nt/AppData/Roaming/SilVerPLuM/profiles/default/savegame-backups/Nith_116719534/05-11-2016-16-36-11/Nith_116719534
[INFO]	savegame	load	load	UID is in C:/Users/fl1nt/AppData/Roaming/SilVerPLuM/profiles/default/savegame-backups/Nith_116719534/05-11-2016-16-36-11/Nith_116719534
[INFO]	savegame	load	load	UID is 116719534
[INFO]	savegame	load	load	UID is 116719534
[INFO]	backup-savegame	init	load	Ended loading savegame
[INFO]	backup-savegame	init	load	Ended loading savegame
`
Windows Version: Windows 10 Pro with Anniversary Update
Silverplum 1.3.2.0
SDV 1.11

Havent got to trying any mods yet, so nope no mods.

**Comment by rumangerst** [comment]
I really would recommend pastebin.com. Nobody can read that

**Comment by 1321302** [comment]
Just running Silverplum from its .exe or steam.  This comes up when crashing.
![silverplum error](https://cloud.githubusercontent.com/assets/11423935/20032167/45c04bd4-a385-11e6-8efe-029c5fa1cc57.JPG)

**Comment by rumangerst** [comment]
OK. Lead me to the exact location where it happens. Looking into it.

**Comment by rumangerst** [comment]
Can you try this Silverplum executable? https://drive.google.com/open?id=0B3c8rHzBL-BiVVNrejFvMU9zU0U (Version number should say 1.3.2.2)

**Comment by 1321302** [comment]
That fixed it, thanks a lot =)

**Comment by rumangerst** [comment]
It seems that Windows doesn't like Qt's progress dialog :)
