### ISSUE TITLE
Missing libquazip5.

### ISSUE THREAD

**Issue by Draconicrose** [rumangerst/SilVerPLuM#2]
I tried running the latest pre-package, but got:
`error while loading shared libraries: libquazip5.so.1: cannot open shared object file: No such file or directory`
So, after some Googling, I ran:
`sudo apt-get install libquazip1`
but no dice. Same error.

**Comment by rumangerst** [comment]
Seems to be some incompatibility between Arch and Debian based systems. It seems that the correct library is called `libquazip-qt5-1`. I've found this here: https://packages.debian.org/jessie/libs/libquazip-qt5-1. But I also found this here: https://packages.debian.org/search?keywords=libquazip5-1

Unfortunately I don't have a Debian-based system here to check it (my Laptop doesn't work well with VMs). 

Let me know if you could find this package and if it works. If nothing helps, I'll investigate when I'm getting to a more beefy computer (today).

**Comment by rumangerst** [comment]
I'm working on it. I'll update the releases that contain some nice things.

**Comment by rumangerst** [comment]
OK. I got it to run on Linux Mint. I had to include Qt 5.7 (and to be sure quazip5) as libraries. Just re-download the newest release and start SilVerPLuM using the \*.sh file. Doesn't look pretty, but works.

If you are using Ubuntu, nag them why they didn't include Qt 5.7, but [Linux 4.8](http://www.theregister.co.uk/2016/10/05/linus_torvalds_admits_buggy_crap_made_it_into_linux_48/)
